### ISSUE TITLE
not working at new installation

### ISSUE THREAD

**Issue by Homoran** [Pmant/ioBroker.harmony#2]
Wie im Forum beschrieben:
http://forum.iobroker.net/viewtopic.php?f=23&p=11441&sid=9c3de9b2b1cc431778343cdc3822e005#p11359

nach einer komplett neuen Installation:
```
<code>2015-09-16 19:08:51.769  - info: harmony.0 starting. Version 0.5.2 in /opt/iobroker/node_modules/iobroker.harmony
2015-09-16 19:08:51.846  - info: harmony.0 hub not initialized
2015-09-16 19:08:53.033  - info: harmony.0 discovered Kino
2015-09-16 19:08:54.451  - error: uncaught exception: Cannot read property 'identity' of undefined
2015-09-16 19:08:54.455  - error: TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous> (/opt/iobroker/node_modules/iobroker.harmony/node_modules/harmonyhubjs-client/lib/login/hub.js:63:15)
    at Client.EventEmitter.emit (events.js:95:17)
    at Client.onStanza (/opt/iobroker/node_modules/iobroker.harmony/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/index.js:224:14)
    at Connection.EventEmitter.emit (events.js:95:17)
    at Connection.onStanza (/opt/iobroker/node_modules/iobroker.harmony/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:370:14)
    at StreamParser.<anonymous> (/opt/iobroker/node_modules/iobroker.harmony/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:226:14)
    at StreamParser.EventEmitter.emit (events.js:95:17)
    at SaxLtx.<anonymous> (/opt/iobroker/node_modules/iobroker.harmony/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:59:22)
    at SaxLtx.EventEmitter.emit (events.js:95:17)
    at SaxLtx._handleTagOpening (/opt/iobroker/node_modules/iobroker.harmony/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/lib/parsers/ltx.js:30:18)
2015-09-16 19:08:54.757  - info: harmony.0 terminating
2015-09-16 19:08:54.773  - error: host.odroid-wheezy instance system.adapter.harmony.0 terminated with code 6 (uncaught exception)
2015-09-16 19:08:54.774  - info: host.odroid-wheezy Restart adapter system.adapter.harmony.0 because enabled
2015-09-16 19:09:16.048  - info: host.odroid-wheezy instance system.adapter.harmony.0 started with pid 3847</code>
```

**Comment by Pmant** [comment]
geht es bei dir mit der neuen Version? Das ist leider ein großes Chaos alles im Moment.
