### ISSUE TITLE
Harmony hub doesn't Install 

### ISSUE THREAD

**Issue by lysander-ll** [Pmant/ioBroker.harmony#30]
I Cant install the hub, this is my instalation text:

$ ./iobroker add harmony  --host raspberrypi
npm install iobroker.harmony --production --prefix "/opt/iobroker" (System call)
npm WARN addRemoteGit Error: not found: gitnpm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git+https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser resetting remote /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }

npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/swissmanu/ltx.git /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefinednpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/swissmanu/ltx.git /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefined

npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR!
 Linux 4.14.52-v7+npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.harmony" "--production" "--prefix" "/opt/iobroker"
npm ERR! node v6.14.1

npm ERR! npm  v3.10.10npm ERR! code ENOGIT

npm ERR! not found: gitnpm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

host.raspberrypi install adapter harmony
npm install iobroker.harmony --production --prefix "/opt/iobroker" (System call)
npm
 WARN addRemoteGit Error: not found: gitnpm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git+https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser resetting remote /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }

npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/swissmanu/ltx.git /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefinednpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/swissmanu/ltx.git /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefined

npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! Linux 4.14.52-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.harmony" "--production" "--prefix" "/opt/iobroker"npm ERR! node
 v6.14.1npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: gitnpm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:npm ERR!     /npm-debug.log

host.raspberrypi install adapter harmony
npm install iobroker.harmony --production --prefix "/opt/iobroker" (System call)
npm
 WARN addRemoteGit Error: not found: gitnpm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git+https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser resetting remote /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }

npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/swissmanu/ltx.git /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefinednpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/swissmanu/ltx.git /root/.npm/_git-remotes/git-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefined

npm
 WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm 
ERR! Linux 4.14.52-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.harmony" "--production" "--prefix" "/opt/iobroker"npm ERR! node v6.14.1
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm
 ERR! not found: gitnpm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:npm ERR!     /npm-debug.log

host.raspberrypi install adapter harmony
ERROR: host.raspberrypi Cannot install harmony
ERROR: process exited with code 13

**Comment by GermanBluefox** [comment]
@swissmanu @Pmant 
This line 
https://github.com/swissmanu/harmonyhubjs-client/blob/develop/package.json#L30

must be replaced with 

`"ltx": "https://github.com/swissmanu/ltx/tarball/cdata-for-ltx-parser"`

It allows the installation without git.

**Comment by Master6726** [comment]
habe das selbe Problem, leider lässt sich die node-xmpp nicht finden um die Änderung durchzuführen, gibt es noch eine andere Möglichkeit den Hub wieder (ist ja schon bis letzte Woche gelaufen) zum laufen zu bekommen ?
