### ISSUE TITLE
Adapter findet Hub nicht mehr

### ISSUE THREAD

**Issue by pfleiderer** [Pmant/ioBroker.harmony#38]
Seit dem ich auf den Neuen Harmony skill gewechselt habe findet der Adapter den Hub nicht mehr.
Anfangs ging es noch, plötzlich ( ich weiss, in der DV gibt es kein plötzlich, ich kann nur keinen Grund erkennen) kommt die Fehlermeldung "(CONNECT] Could not connect to Hapes Harmony: Error: connect ECONNREFUSED 192.168.178.102:5222"
Löschen und Neuinstallation bringt keine Änderung. Auch Reset des Adapters funktioniert nicht.

**Comment by Leviathan09** [comment]
Gleiches Problem tritt bei mir auch auf

harmony.0 [CONNECT] Could not connect to HarmonyHub: Error: connect ECONNREFUSED 192.168.1.34:5222.

**Comment by serex81** [comment]
I have the same issue
Npm 6.4.1
node v8.14.0

**Comment by Pmant** [comment]
Logitech closed the XMPP-Port on the Harmony-Hub.
Please check [forum thread](https://forum.iobroker.net/viewtopic.php?f=20&t=19637)

**Comment by pfleiderer** [comment]
#Tkx... i've just seen it. I've done a firmware downgrad, and for now it is doing well again hoping for some changes on the logitech side...

**Comment by marvingrieger** [comment]
Unfortunately, it does not look good ...

https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

**Comment by Pmant** [comment]
Bitte die neue Version testen. Dazu in ioBroker von GitHub installieren und eine **eigene URL** eingeben:
`https://github.com/Pmant/ioBroker.harmony/tarball/WS`

**Comment by Pmant** [comment]
@foxriver76 ich wusste nicht, dass du auch schon dran warst. Wenn es dir nichts ausmacht kannst du gern https://github.com/foxriver76/ioBroker.harmony/commit/4deaf453d200482a90bb18cc564ae06ff1667bf2 für die neue Version aufbereiten.

**Comment by foxriver76** [comment]
Ja hatte mich auch an den Websockets versucht, allerdings in dem Fall war ich da durch meine kurze JS Erfahrung wesentlich langsamer als du. :+1: 
Werde die zwei Kleinigkeiten mal als PR einreichen.

**Comment by foxriver76** [comment]
Bekomme allerdings noch folgenden Fehler:
```
2018-12-21 04:17:56.824  - info: harmony.0 starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.harmony, node: v8.14.0
--
2018-12-21 04:17:56.864  - info: harmony.0 [DISCOVER] Searching for Harmony Hubs on 192.168.178.22
2018-12-21 04:17:57.355  - info: harmony.0 [DISCOVER] Discovered Moritz (192.168.178.22) and will try to connect
2018-12-21 04:17:57.419  - info: harmony.0 [CONNECT] Connecting to Moritz (192.168.178.22)
2018-12-21 04:18:01.080  - error: harmony.0 uncaught exception: domain.enter is not a function
2018-12-21 04:18:01.081  - error: harmony.0 TypeError: domain.enter is not a function
at HarmonyWS.emit (events.js:199:12)
at HarmonyWS.parseMessage (/opt/iobroker/node_modules/iobroker.harmony/lib/HarmonyWS.js:94:30)
at WebSocket.socket.on (/opt/iobroker/node_modules/iobroker.harmony/lib/HarmonyWS.js:66:22)
at emitOne (events.js:116:13)
at WebSocket.emit (events.js:211:7)
at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.harmony/node_modules/ws/lib/websocket.js:741:20)
at emitOne (events.js:116:13)
at Receiver.emit (events.js:211:7)
at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.harmony/node_modules/ws/lib/receiver.js:417:14)
at Receiver.getData (/opt/iobroker/node_modules/iobroker.harmony/node_modules/ws/lib/receiver.js:347:17)
2018-12-21 04:18:01.083  - info: harmony.0 [END] Terminating
2018-12-21 04:18:01.095  - info: harmony.0 terminating
2018-12-21 04:18:01.122  - error: Caught by controller[0]: TypeError: domain.enter is not a function
2018-12-21 04:18:01.123  - error: Caught by controller[0]:     at HarmonyWS.emit (events.js:199:12)
2018-12-21 04:18:01.123  - error: Caught by controller[0]:     at HarmonyWS.parseMessage (/opt/iobroker/node_modules/iobroker.harmony/lib/HarmonyWS.js:94:30)
2018-12-21 04:18:01.123  - error: Caught by controller[0]:     at WebSocket.socket.on (/opt/iobroker/node_modules/iobroker.harmony/lib/HarmonyWS.js:66:22)
2018-12-21 04:18:01.123  - error: Caught by controller[0]:     at emitOne (events.js:116:13)
2018-12-21 04:18:01.124  - error: Caught by controller[0]:     at WebSocket.emit (events.js:211:7)
2018-12-21 04:18:01.124  - error:  Caught by controller[0]:     at Receiver.receiverOnMessage  (/opt/iobroker/node_modules/iobroker.harmony/node_modules/ws/lib/websocket.js:741:20)
2018-12-21 04:18:01.124  - error: Caught by controller[0]:     at emitOne (events.js:116:13)
2018-12-21 04:18:01.124  - error: Caught by controller[0]:     at Receiver.emit (events.js:211:7)
2018-12-21 04:18:01.124  - error:  Caught by controller[0]:     at Receiver.dataMessage  (/opt/iobroker/node_modules/iobroker.harmony/node_modules/ws/lib/receiver.js:417:14)
2018-12-21 04:18:01.124  - error:  Caught by controller[0]:     at Receiver.getData  (/opt/iobroker/node_modules/iobroker.harmony/node_modules/ws/lib/receiver.js:347:17)
2018-12-21 04:18:01.125  - error: host.ioBroker-Rock64 instance system.adapter.harmony.0 terminated with code 0 (OK)
```

**Comment by Pmant** [comment]
schau mal bitte hier
https://github.com/adafruit/node_mpr121/pull/8
und hier
https://github.com/mysqljs/mysql/issues/1949

hat es etwas damit zu tun (i2c-bus)?

**Comment by Pmant** [comment]
Konnte es nun auf einem Linuxsystem mit node 6 reproduzieren und beheben.

**Comment by foxriver76** [comment]
Hm also ich habe Node 8.14 drauf. Mit Node 8 lief er bei dir unter Linux?

**Comment by foxriver76** [comment]
Geht jetzt jedenfalls. Top :+1:

**Comment by foxriver76** [comment]
Wenn die Activity -1 (aus) ist, gibt es noch eine Warning:  ```[SETACTIVITY] Unknown activityId: -1```

**Comment by Leviathan09** [comment]
Die Installation lief ohne Probleme durch, mir wird jedoch kein Adapter angezeigt.

./iobroker url "https://github.com/Pmant/ioBroker.harmony/tarball/WS" --debug
install https://github.com/Pmant/ioBroker.harmony/tarball/WS
npm install https://github.com/Pmant/ioBroker.harmony/tarball/WS --production --save --prefix "/opt/iobroker" (System call)
npm
 WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

+ iobroker.harmony@1.1.0added 21 packages from 54 contributors and audited 4687 packages in 51.732s

found 46 vulnerabilities (33 low, 2 moderate, 11 high)  run `npm audit fix` to fix them, or `npm audit` for details

process exited with code 0

**Comment by Pmant** [comment]
> Wenn die Activity -1 (aus) ist, gibt es noch eine Warning: `[SETACTIVITY] Unknown activityId: -1`

Ja, der erste Status kommt schon rein, bevor die Config eingelesen wurde. Ist nicht weiter schlimm, habe die Meldung auf debug runtergestuft. 

>Die Installation lief ohne Probleme durch, mir wird jedoch kein Adapter angezeigt.

Ich glaube die NPM-Warnung hat nichts mit diesem Adapter zu tun. Wenn du von GitHub installierst wird nicht automatisch eine Instanz des Adapter erstellt. Klick mal unter Adapter auf das "+" bei Harmony, dann sollte die Instanz angelegt werden. Ggf. auch noch den Upload-Button betätigen.

**Comment by Pmant** [comment]
Ich schließe hier erstmal, für neue Probleme dann bitte jeweils gezielt Issues erstellen.
